### ISSUE TITLE
HAve tried multiple times to submit but this account denies attempts

### ISSUE THREAD

**Issue by devnic13** [RaidAndFade/Hacktoberfest2018#110]
Why can't I push my code up or initiate a pull request?

**Comment by RaidAndFade** [comment]
I can't find any forks of this repo in your account, are you sure you are committing properly?

**Comment by devnic13** [comment]
Nope.  Apparently not!  LOL  Going to try again.  Thanks.

**Comment by RaidAndFade** [comment]
Going to close this as resolved since it looks like you managed to create a PR (#115)
