### ISSUE TITLE
front page design

### ISSUE THREAD

**Issue by lazycipher** [RaidAndFade/Hacktoberfest2018#29]
I would like to work on the front page of the website.

**Comment by RaidAndFade** [comment]
As long as the content remains the same, feel free

**Comment by RaidAndFade** [comment]
By content i mean the js script and the list

**Comment by lazycipher** [comment]
cool ! Let me give it a try !!

**Comment by RaidAndFade** [comment]
This has been resolved. Thanks for the input @lazycipher and @NCPlayz
